//Coded and values found mainly by Kuno Demetries, with moral support and puppetry by Streetbackguy
state("deadrising4")
{
    int Loading : 0x3352C54;
    int MGSummary : 0x337A3F0;
    int MainMenu : 0x2119950;
    long CurObj : 0x028620F0, 0x20, 0x3A8, 0x4E0, 0x78, 0x858, 0x2F0, 0x708;
}

init
{
    vars.doneMaps = new List<string>();
    vars.CurObj = "";
}

startup
{
    settings.Add("DR4", true, "Dead Rising 4");
        settings.Add("C0", true, "Case 0: Minigolf Night", "DR4");
        settings.Add("C1", true, "Case 1: Door Crasher Special", "DR4");
        settings.Add("C2", true, "Case 2: Invasion on Main Street", "DR4");
        settings.Add("C3", true, "Case 3: Shit's Getting Science", "DR4");
        settings.Add("C4", true, "Case 4: Drop the Base", "DR4");
        settings.Add("C5", true, "Case 5: Man of the Year", "DR4");
        settings.Add("C6", true, "Case 6: Eye on the Prize", "DR4");
        settings.Add("FR", true, "Frank Rising", "DR4");
        settings.Add("MG", true, "Super Ultra Dead Rising 4 Mini Golf", "DR4");
            settings.Add("minigolf", false, "Split on each Course Summary Screen", "MG");

    var tB = (Func<string, string, string, Tuple<string, string, string>>) ((elmt1, elmt2, elmt3) => { return Tuple.Create(elmt1, elmt2, elmt3); });
        var sB = new List<Tuple<string, string, string>> 
    {
        tB("C0", "1", "Investigate the base"),
        tB("C0", "2", "Find the keycard"),
        tB("C0", "3", "Sneak into the base"),
        tB("C0", "4", "Explore the base"),
        tB("C0", "5", "Kill the zombie"),
        tB("C0", "6", "Keep exploring"),
        tB("C0", "7", "Pick up a weapon"),
        tB("C0", "8", "Kill the released zombies"),
        tB("C0", "9", "Pick up a second weapon"),
        tB("C0", "10", "Kill the zombies"),
        tB("C0", "11", "Solve the investigation"),
        tB("C0", "12", "Look for evidence"),
        tB("C0", "13", "Tag the controls"),
        tB("C0", "14", "Incinerate the zombie"),
        tB("C0", "15", "Investigate the morgue"),
        tB("C0", "16", "Follow Vick"),
        tB("C0", "17", "Find a way out"),
        tB("C0", "18", "Pick up the Blueprint"),
        tB("C0", "19", "Pick up the ingredients"),
        tB("C1", "20", "Defend Brad"),
        tB("C1", "21", "Clear out the zombies"),
        tB("C1", "22", "Talk to Brad"),
        tB("C1", "23", "Meet Brad at the hotel"),
        tB("C1", "24", "Talk to Connor"),
        tB("C1", "25", "Defeat the soldiers"),
        tB("C1", "26", "Follow Brad"),
        tB("C1", "27", "Find the mall security center"),
        tB("C1", "28", "Kill the fresh infected"),
        tB("C1", "29", "Locate Vick’s hideout"),
        tB("C1", "30", "Talk to the survivors"),
        tB("C1", "31", "Purchase a map"),
        tB("C1", "32", "Get to Medieval Village"),
        tB("C1", "33", "Antagonize hostile survivors"),
        tB("C1", "34", "Exit Medieval Village"),
        tB("C1", "35", "Clear the area"),
        tB("C1", "36", "Enter the quarantine area"),
        tB("C1", "37", "Investigate the area"),
        tB("C1", "38", "Talk to Darcy"),
        tB("C2", "39", "Meet up with Paula"),
        tB("C2", "40", "Pick up the blueprint"),
        tB("C2", "41", "Combo the vehicles"),
        tB("C2", "42", "Investigate the archives"),
        tB("C2", "43", "Talk to Paula"),
        tB("C2", "44", "Find the drug store"),
        tB("C2", "45", "Get into the apartment"),
        tB("C2", "46", "Investigate the apartment"),
        tB("C2", "47", "Listen to the radio"),
        tB("C2", "48", "Go to the fire hall"),
        tB("C2", "49", "Discover what happened"),
        tB("C2", "50", "Clear the fire hall"),
        tB("C2", "51", "Investigate the fire hall"),
        tB("C2", "52", "Enter the junkyard"),
        tB("C2", "53", "Infiltrate the junkyard"),
        tB("C2", "54", "Go to West Ridge"),
        tB("C2", "55", "Talk to Isaac"),
        tB("C2", "56", "Find Hammond"),
        tB("C2", "57", "Follow Hammond"),
        tB("C2", "58", "Defeat Obscuris"),
        tB("C2", "59", "Enter the dam"),
        tB("C2", "60", "Clear out Obscuris soldiers"),
        tB("C2", "61", "Turn on the lights"),
        tB("C2", "62", "Investigate the dam"),
        tB("C2", "63", "Find the trap"),
        tB("C2", "64", "Defeat the lieutenant"),
        tB("C3", "65", "Pursue the convoy"),
        tB("C3", "66", "Talk to the convoy survivor"),
        tB("C3", "67", "Go to the emergency shelter"),
        tB("C3", "68", "Search for morphine"),
        tB("C3", "69", "Trade morphine for intel"),
        tB("C3", "70", "Investigate the wreckage"),
        tB("C3", "71", "Exit through the gate"),
        tB("C3", "72", "Follow the wreckage"),
        tB("C3", "73", "Follow the monster"),
        tB("C3", "74", "Defeat the strange zombie"),
        tB("C3", "75", "Kill the remaining zombies"),
        tB("C3", "76", "Listen to the call"),
        tB("C3", "77", "Meet with Dr. Blackburne"),
        tB("C3", "78", "Defeat the Obscuris soldiers"),
        tB("C3", "79", "Enter the house"),
        tB("C3", "80", "Interview Dr. Blackburne"),
        tB("C3", "81", "Photograph the picture"),
        tB("C3", "82", "Grab the Exo Suit"),
        tB("C3", "83", "Upgrade Exo Suit"),
        tB("C3", "84", "Open the garage door"),
        tB("C3", "85", "Escape the gated community"),
        tB("C3", "86", "Go to the winery"),
        tB("C3", "87", "Find Barnaby’s lab"),
        tB("C3", "88", "Investigate the lab"),
        tB("C3", "89", "Inspect the door"),
        tB("C3", "90", "Examine the machine"),
        tB("C3", "91", "Survive"),
        tB("C3", "92", "Escape the room"),
        tB("C4", "93", "Leave the winery"),
        tB("C4", "94", "Find Hammond in West Ridge"),
        tB("C4", "95", "Search the house"),
        tB("C4", "96", "Go to the pool hall"),
        tB("C4", "97", "Go to the army base"),
        tB("C4", "98", "Grab the explosives"),
        tB("C4", "99", "Find the weak spot"),
        tB("C4", "100", "Plant explosives"),
        tB("C4", "101", "Defend Hammond"),
        tB("C4", "102", "Equip the Exo Suit"),
        tB("C4", "103", "Sabotage the Comm Tower"),
        tB("C4", "104", "Defeat Obscuris soldiers"),
        tB("C4", "105", "Open the gate"),
        tB("C4", "106", "Sabotage the turret control"),
        tB("C4", "107", "Open gate"),
        tB("C4", "108", "Sabotage the generator"),
        tB("C4", "109", "Enter the building"),
        tB("C4", "110", "Search the building"),
        tB("C4", "111", "Investigate the gym"),
        tB("C4", "112", "Find the intelligence lockup"),
        tB("C4", "113", "Discover Barnaby’s secrets"),
        tB("C4", "114", "Find the recon footage"),
        tB("C4", "115", "Watch the recon footage"),
        tB("C4", "116", "Escape the base"),
        tB("C4", "117", "Defeat the Commander"),
        tB("C5", "118", "Go to the West Ridge shelter"),
        tB("C5", "119", "Scout out the shelter"),
        tB("C5", "120", "Investigate the lockdown"),
        tB("C5", "121", "Find the panel"),
        tB("C5", "122", "Override the lockdown"),
        tB("C5", "123", "Enter the emergency shelter"),
        tB("C5", "124", "Clear out all the enemies"),
        tB("C5", "125", "Go to Tom’s farm"),
        tB("C5", "126", "Search for Hammond"),
        tB("C5", "127", "Open the secret door"),
        tB("C5", "128", "Investigate the secret room"),
        tB("C5", "129", "Go to the cement factory"),
        tB("C5", "130", "Find a way to the top"),
        tB("C5", "131", "Find Tom & Hammond"),
        tB("C5", "132", "Defeat Tom"),
        tB("C5", "133", "Go to the elevator"),
        tB("C5", "134", "Talk to Jordan"),
        tB("C5", "135", "Get the explosives"),
        tB("C5", "136", "Head into the sewers"),
        tB("C5", "137", "Plant the explosive"),
        tB("C5", "138", "Track Calder"),
        tB("C5", "139", "Retrieve the hard drive"),
        tB("C5", "140", "Escape the area"),
        tB("C5", "141", "Escape from Calder"),
        tB("C6", "142", "Get the camera back"),
        tB("C6", "143", "Cut Vick off at Kiichiro Plaza"),
        tB("C6", "144", "Defeat Calder"),
        tB("C6", "145", "Fight Calder"),
        tB("C6", "146", "Fight off Calder’s zombies"),
        tB("C6", "147", "Survive with Vick and Brad"),
        tB("FR", "148", "Kill the humans"),
        tB("FR", "149", "Satisfy your hunger"),
        tB("FR", "150", "Hunt for prey"),
        tB("FR", "151", "Listen to the conversation"),
        tB("FR", "152", "Find the key"),
        tB("FR", "153", "Open the door"),
        tB("FR", "154", "Follow Blackburne"),
        tB("FR", "155", "Enter the mall"),
        tB("FR", "156", "Follow Blackburne’s directions"),
        tB("FR", "157", "Approach Calder’s corpse"),
        tB("FR", "158", "Collect the swarm"),
        tB("FR", "159", "Follow the green glow"),
        tB("FR", "160", "Investigate the lone wasp"),
        tB("FR", "161", "Leave the shelter"),
        tB("FR", "162", "Search Dodd’s Drugs"),
        tB("FR", "163", "Find painkillers"),
        tB("FR", "164", "Search Cochrane’s Pub"),
        tB("FR", "165", "Find the control key"),
        tB("FR", "166", "Search Big Buck’s"),
        tB("FR", "167", "Find the solenoids"),
        tB("FR", "168", "Wait for Blackburne’s instructions"),
        tB("FR", "169", "Search Rockpile Liquor"),
        tB("FR", "170", "Find overproof liquor"),
        tB("FR", "171", "Search the bus depot"),
        tB("FR", "172", "Travel to West Ridge"),
        tB("FR", "173", "Go to the school"),
        tB("FR", "174", "Defeat the evo zombies"),
        tB("FR", "175", "Collect the wasp queen"),
        tB("FR", "176", "Listen to Hammond"),
        tB("FR", "177", "Clear out the winery"),
        tB("FR", "178", "Find Blackburne"),
        tB("FR", "179", "Talk to Blackburne"),
        tB("FR", "180", "Head through the airlock"),
        tB("FR", "181", "Place the queen in containment"),
        tB("FR", "182", "Synthesize the aerosol"),
        tB("FR", "183", "Administer the aerosol"),
        tB("FR", "184", "Install the solenoids"),
        tB("FR", "185", "Reroute the power"),
        tB("FR", "186", "Vent the gas"),
        tB("FR", "187", "Activate the treatment chamber"),
        tB("FR", "188", "Enter the treatment chamber"),
    };
    foreach (var s in sB) settings.Add(s.Item2, false, s.Item3, s.Item1);

vars.Splits = new Dictionary <string, string>
    {
        {"Investigate the base", "1"},
        {"Find the keycard", "2"},
        {"Sneak into the base", "3"},
        {"Explore the base", "4"},
        {"Kill the zombie", "5"},
        {"Keep exploring", "6"},
        {"Kill the released zombies", "7"},
        {"Pick up a second weapon", "8"},
        {"Kill the zombies", "9"},
        {"Solve the investigation", "10"},
        {"Look for evidence", "11"},
        {"Tag the controls", "12"},
        {"Incinerate the zombie", "13"},
        {"Investigate the morgue", "14"},
        {"Follow Vick", "15"},
        {"Find a way out", "16"},
        {"Pick up the Blueprint", "17"},
        {"Pick up the ingredients", "18"},
        {"Defend Brad", "20"},
        {"Clear out the zombies", "21"},
        {"Talk to Brad", "22"},
        {"Meet Brad at the hotel", "23"},
        {"Talk to Connor", "24"},
        {"Defeat the soldiers", "25"},
        {"Follow Brad", "26"},
        {"Find the mall security center", "27"},
        {"Kill the fresh infected", "28"},
        {"Locate Vick’s hideout", "29"},
        {"Talk to the survivors", "30"},
        {"Purchase a map", "31"},
        {"Get to Medieval Village", "32"},
        {"Antagonize hostile survivors", "33"},
        {"Exit Medieval Village", "34"},
        {"Clear the area", "35"},
        {"Enter the quarantine area", "36"},
        {"Investigate the area", "37"},
        {"Talk to Darcy", "38"},
        {"Meet up with Paula", "39"},
        {"Pick up the blueprint", "40"},
        {"Combo the vehicles", "41"},
        {"Investigate the archives", "42"},
        {"Talk to Paula", "43"},
        {"Find the drug store", "44"},
        {"Get into the apartment", "45"},
        {"Investigate the apartment", "46"},
        {"Listen to the radio", "47"},
        {"Go to the fire hall", "48"},
        {"Discover what happened", "49"},
        {"Clear the fire hall", "50"},
        {"Investigate the fire hall", "51"},
        {"Enter the junkyard", "52"},
        {"Infiltrate the junkyard", "53"},
        {"Go to West Ridge", "54"},
        {"Talk to Isaac", "55"},
        {"Find Hammond", "56"},
        {"Follow Hammond", "57"},
        {"Defeat Obscuris", "58"},
        {"Enter the dam", "59"},
        {"Clear out Obscuris soldiers", "60"},
        {"Turn on the lights", "61"},
        {"Investigate the dam", "62"},
        {"Find the trap", "63"},
        {"Defeat the lieutenant", "64"},
        {"Pursue the convoy", "65"},
        {"Talk to the convoy survivor", "66"},
        {"Go to the emergency shelter", "67"},
        {"Search for morphine", "68"},
        {"Trade morphine for intel", "69"},
        {"Investigate the wreckage", "70"},
        {"Exit through the gate", "71"},
        {"Follow the wreckage", "72"},
        {"Follow the monster", "73"},
        {"Defeat the strange zombie", "74"},
        {"Kill the remaining zombies", "75"},
        {"Listen to the call", "76"},
        {"Meet with Dr. Blackburne", "77"},
        {"Defeat the Obscuris soldiers", "78"},
        {"Enter the house", "79"},
        {"Interview Dr. Blackburne", "80"},
        {"Photograph the picture", "81"},
        {"Grab the Exo Suit", "82"},
        {"Upgrade Exo Suit", "83"},
        {"Open the garage door", "84"},
        {"Escape the gated community", "85"},
        {"Go to the winery", "86"},
        {"Find Barnaby’s lab", "87"},
        {"Investigate the lab", "88"},
        {"Inspect the door", "89"},
        {"Examine the machine", "90"},
        {"Survive", "91"},
        {"Escape the room", "92"},
        {"Leave the winery", "93"},
        {"Find Hammond in West Ridge", "94"},
        {"Search the house", "95"},
        {"Go to the pool hall", "96"},
        {"Go to the army base", "97"},
        {"Grab the explosives", "98"},
        {"Find the weak spot", "99"},
        {"Plant explosives", "100"},
        {"Defend Hammond", "101"},
        {"Equip the Exo Suit", "102"},
        {"Sabotage the Comm Tower", "103"},
        {"Defeat Obscuris soldiers", "104"},
        {"Open the gate", "105"},
        {"Sabotage the turret control", "106"},
        {"Open gate", "107"},
        {"Sabotage the generator", "108"},
        {"Enter the building", "109"},
        {"Search the building", "110"},
        {"Investigate the gym", "111"},
        {"Find the intelligence lockup", "112"},
        {"Discover Barnaby’s secrets", "113"},
        {"Find the recon footage", "114"},
        {"Watch the recon footage", "115"},
        {"Escape the base", "116"},
        {"Defeat the Commander", "117"},
        {"Go to the West Ridge shelter", "118"},
        {"Scout out the shelter", "119"},
        {"Find the panel", "120"},
        {"Override the lockdown", "121"},
        {"Enter the emergency shelter", "122"},
        {"Clear out all the enemies", "123"},
        {"Go to Tom’s farm", "124"},
        {"Search for Hammond", "125"},
        {"Open the secret door", "126"},
        {"Investigate the secret room", "127"},
        {"Go to the cement factory", "128"},
        {"Find a way to the top", "129"},
        {"Find Tom & Hammond", "130"},
        {"Defeat Tom", "131"},
        {"Go to the elevator", "132"},
        {"Talk to Jordan", "133"},
        {"Get the explosives", "134"},
        {"Head into the sewers", "135"},
        {"Plant the explosive", "136"},
        {"Track Calder", "137"},
        {"Retrieve the hard drive", "138"},
        {"Escape the area", "139"},
        {"Escape from Calder", "140"},
        {"Get the camera back", "141"},
        {"Cut Vick off at Kiichiro Plaza", "142"},
        {"Defeat Calder", "143"},
        {"Fight Calder", "144"},
        {"Fight off Calder’s zombies", "145"},
        {"Survive with Vick and Brad", "146"},
        {"Kill the humans", "147"},
        {"Satisfy your hunger", "148"},
        {"Hunt for prey", "149"},
        {"Listen to the conversation", "150"},
        {"Find the key", "151"},
        {"Open the door", "152"},
        {"Follow Blackburne", "153"},
        {"Enter the mall", "154"},
        {"Follow Blackburne’s directions", "155"},
        {"Approach Calder’s corpse", "156"},
        {"Collect the swarm", "157"},
        {"Follow the green glow", "158"},
        {"Investigate the lone wasp", "159"},
        {"Leave the shelter", "160"},
        {"Search Dodd’s Drugs", "161"},
        {"Find painkillers", "162"},
        {"Search Cochrane’s Pub", "163"},
        {"Find the control key", "164"},
        {"Search Big Buck’s", "165"},
        {"Find the solenoids", "166"},
        {"Wait for Blackburne’s instructions", "167"},
        {"Search Rockpile Liquor", "168"},
        {"Find overproof liquor", "169"},
        {"Search the bus depot", "170"},
        {"Travel to West Ridge", "171"},
        {"Go to the school", "172"},
        {"Defeat the evo zombies", "173"},
        {"Collect the wasp queen", "174"},
        {"Go to Tom's farm", "175"},
        {"Listen to Hammond", "176"},
        {"Clear out the winery", "177"},
        {"Find Blackburne", "178"},
        {"Talk to Blackburne", "179"},
        {"Head through the airlock", "180"},
        {"Place the queen in containment", "181"},
        {"Synthesize the aerosol", "182"},
        {"Administer the aerosol", "183"},
        {"Install the solenoids", "184"},
        {"Reroute the power", "185"},
        {"Vent the gas", "186"},
        {"Activate the treatment chamber", "187"},
        {"Enter the treatment chamber", "188"},
        {"Tuez les humains", "147"},
        {"Mangez à votre","148"},
        {"Chassez une proie", "149"},
        {"Écoutez la conversation","150"},
        {"Trouvez la clé","151"},
        {"Entrez dans la galerie","154"},
        {"Suivez les instructions de Blackburne","155"},
        {"Approchez du cadavre de Calder","156"},
        {"Récupérez l'essaim","157"},
        {"Suivez la lueur verte","158"},
        {"Enquêtez sur la guêpe solitaire","159"},
        {"Quittez l'abri","160"},
        {"Fouillez Dodd's Drugs","161"},
        {"Trouvez les antidouleurs","162"},
        {"Fouillez le Cochrane's Pub","163"},
        {"Trouvez la clé de contrôle","164"},
        {"Fouillez Big Buck's","165"},
        {"Trouvez les solénoïdes","166"},
        {"Attendez les instructions de Blackburne","167"},
        {"Trouvez de l'alcool fort","169"},
        {"Fouillez le dépôt de bus","170"},
        {"Allez à West Ridge","171"},
        {"Allez à l'école","172"},
        {"Battez les zombies évolués.","173"},
        {"Récupérez la reine guêpe","174"},
        {"Allez à la ferme de Tom","175"},
        {"Écoutez Hammond","176"},
        {"Rendez-vous à la vinerie","177"},
        {"Trouvez Blackburne","178"},
        {"Parlez à Blackburne","179"},
        {"Traversez le sas","180"},
        {"Placez la reine en isolement","181"},
        {"Synthétisez l'aérosol","182"},
        {"Administrez l'aérosol","183"},
        {"Installez les solénoïdes","184"},
        {"Redirigez le courant","185"},
        {"Évacuez le gaz","186"},
        {"Activez la chambre de traitement", "187"},
        {"Entrez dans la chambre", "188"},
    };

    if (timer.CurrentTimingMethod == TimingMethod.RealTime)
    {
        var timingMessage = MessageBox.Show (
            "This game uses Time without Loads (Game Time) as the main timing method.\n"+
            "LiveSplit is currently set to show Real Time (RTA).\n"+
            "Would you like to set the timing method to Game Time?",
            "LiveSplit | Dead Rising 4",
            MessageBoxButtons.YesNo, MessageBoxIcon.Question
        );

        if (timingMessage == DialogResult.Yes)
            timer.CurrentTimingMethod = TimingMethod.GameTime;
    }

}

//Starts as soon as you gain control of Frank
start
{
    return (current.Loading == 0 && current.MainMenu == 65 || current.Loading == 16843008);
}

//All of these Loads are to help stop the timer pausing on Pause Menus whilst still pausing on the Mini Golf summary screens.
isLoading
{
    return (current.Loading == 0 || current.Loading == 1 && current.MGSummary == 14072 || current.Loading == 1 && current.MGSummary >= 14160);
}

split
{
    if (settings[vars.Splits[current.CurObj]] && (!vars.doneMaps.Contains(current.CurObj)))
    {
        vars.doneMaps.Add(current.CurObj);
        return true;
    }
}

onStart
{
    timer.IsGameTimePaused = true;
}

reset
{
    return (current.MainMenu == 0 && current.Loading == 1);
}

onReset
{
    vars.doneMaps.Clear();
}
